blank_issues_enabled: true
contact_links:
  - name: New issue
    url: >-
      https://github.com/mallepalliharshavardhan/Local-chatbot-AI/blob/main/CONTRIBUTING.md
    about: "Before opening a new issue, please make sure to read CONTRIBUTING.md"
